name: SLSA build

on:
  push:
  
permissions: read-all

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_gradle_slsa3.yml@v1.9.0
    with:
      artifact-list: ./build/libs/example-spring-boot-helloworld-0.1.1-SNAPSHOT-plain.jar